name: abe haak
favicon: null
layout_spectrum: 0.52959
typography_spectrum: 0.45087953051552176
title: A Philological Diary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181e2a'
    - '#d2a167'
    - '#ac7e4a'
    - '#724f2f'
    - '#cde1e8'
  brandStrength: 0.125
  lightness: 0.7859651355538517
  saturation: 0.9849589227233082
  rhythmicContrast: 0.9518769001588225
purpose: []
