name: abe haak
favicon: null
layout_spectrum: 0.02387544931843877
typography_spectrum: 0.45087953051552176
title: Public Log
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.13314920687116683
  lightness: 0.7859651355538517
  saturation: 0.9849589227233082
  rhythmicContrast: 0.9518769001588225
purpose: []
